name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Build image and save SHA
        run: |
          IMAGE_NAME=my_app:${GITHUB_RUN_ID}
          docker build --build-arg BUILD_ID=$(date +%s) -t $IMAGE_NAME .
          docker inspect --format='{{.Id}}' $IMAGE_NAME > image-sha.txt

      - name: Commit SHA file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add image-sha.txt
          git diff --cached --quiet || git commit -m "Update image SHA [skip ci]"
          git pull --rebase origin main
          git push

      - name: Skip loop
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: echo "Skipping recursive build."
