name: Build Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (force new SHA)
        run: |
          echo "Forcing new Docker build..."
          docker build --no-cache -t my-terraform-app:${GITHUB_RUN_ID} .
          docker inspect --format='{{.Id}}' my-terraform-app:${GITHUB_RUN_ID} > image-sha.txt
          echo "New SHA recorded:"
          cat image-sha.txt

      - name: Commit and push image-sha.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add image-sha.txt
          git diff --cached --quiet && echo "No changes to commit" || git commit -m "Update image SHA [skip ci]"
          git pull --rebase origin main
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prevent workflow loop
        if: contains(github.event.head_commit.message, '[skip ci]')
        run: echo "Skipping workflow run for CI commit."
